name: build application

run-name: ${{ github.actor }} is building App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Handle keystore
        if: ${{ inputs.environment == 'Release' }}
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.asc
          gpg -d --passphrase ${{ secrets.KEYSTORE_PASSPHRASE }} --batch keystore.asc > keystore

          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties.asc
          gpg -d --passphrase ${{ secrets.KEYSTORE_PASSPHRASE }} --batch keystore.properties.asc > keystore.properties

      - name: Run build
        run: ./gradlew assemble${{ inputs.environment }}

      - name: Remove keystore
        if: always()
        run: |
          rm -f keystore keystore.asc keystore.properties.asc keystore.properties

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.workspace }}/app/build/outputs/apk/**/*.apk
          retention-days: 5

      - name: Upload mapping
        uses: actions/upload-artifact@v4
        if: ${{ inputs.environment == 'Release' }}
        with:
          name: mapping
          path: ${{ github.workspace }}/app/build/outputs/mapping
          retention-days: 5

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload detekt report
        uses: actions/upload-artifact@v4
        with:
          name: detekt report
          path: ${{ github.workspace }}/app/build/reports/detekt
          retention-days: 5

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: ./gradlew testDebugUnitTestCoverage

      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests report
          path: |
            ${{ github.workspace }}/app/build/reports/jacoco
            ${{ github.workspace }}/app/build/reports/tests/testDebugUnitTest
          retention-days: 5
