name: feature

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
  DATADOG_APPLICATION_ID: ${{ secrets.DATADOG_APPLICATION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run build
        run: ./gradlew assembleDebug

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload detekt report
        uses: actions/upload-artifact@v4
        with:
          name: detekt report
          path: ${{ github.workspace }}/app/build/reports/detekt
          retention-days: 5

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run unit tests
        run: ./gradlew testDebugUnitTestCoverage

      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests report
          path: |
            ${{ github.workspace }}/app/build/reports/jacoco
            ${{ github.workspace }}/app/build/reports/tests/testDebugUnitTest
          retention-days: 5
