name: feature

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build
        run: ./gradlew assembleDebug

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload detekt report
        uses: actions/upload-artifact@v4
        with:
          name: detekt report
          path: ${{ github.workspace }}/app/build/reports/detekt
          retention-days: 5

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: ./gradlew unitTestCoverage

      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests report
          path: |
            ${{ github.workspace }}/app/build/reports/jacoco
            ${{ github.workspace }}/app/build/reports/tests/testDebugUnitTest
          retention-days: 5
